### ISSUE TITLE
Check for pandoc-citeproc first

### ISSUE THREAD

**Issue by mikelove** [csoneson/countsimQC#1]
I tried to run an analysis on the cluster, and it got through to the final step which involves pandoc-citeproc, but this wasn't found in the path. It would be nice if there were a fast check you could do upstream of the heavy lifting to see if the pandoc-citeproc step will run ok.

**Comment by csoneson** [comment]
I have added a check for pandoc availability in the beginning of `countsimQCReport`. Does that catch the problem?

**Comment by mikelove** [comment]
I have pandoc but not pandoc-citeproc, so this doesn't exactly catch my specific bug.

This may be a rabbit hole but this might work:

```
 > suppressWarnings(err <- system2("pandoc","--version",stdout=FALSE,stderr=FALSE))
 > err
 [1] 0
 > suppressWarnings(err <- system2("pandoc-citeproc","--version",stdout=FALSE,stderr=FALSE))
!> err
 [1] 127
```

**Comment by csoneson** [comment]
Ok, I see. Maybe `Sys.which('pandoc-citeproc')` - what does that return for you?

**Comment by mikelove** [comment]
much better 😆 

```
> Sys.which('pandoc-citeproc')
pandoc-citeproc
             ""
```

**Comment by csoneson** [comment]
Great - I'll add a check for both `pandoc` and `pandoc-citeproc`.

**Comment by csoneson** [comment]
Ok - this is added in 9aba4466e03f1c4d674bdc965b076e99bc349125. I also added an argument `ignorePandoc` to `countsimQCReport()`. If this is set to TRUE, it will give a warning but continue (the figures should still be generated, just not the final report). If FALSE, it should stop. It would be awesome if you could try it out on your system and see if it works as expected (I am not sure we have a system without pandoc :))

**Comment by mikelove** [comment]
This works!

```
 > countsimQCReport(ddsList = list("sim"=dds, "GEUVADIS"=geuvadis),
 +                  outputFile = "countsimReport.html",
 +                  outputDir = "./",
 +                  description = "Comparison of simulated transcript-level counts",
 +                  maxNForCorr = 50,
 +                  maxNForDisp = 50,
 +                  seed = 1,
 +                  calculateStatistics=FALSE)
 Error in countsimQCReport(ddsList = list(sim = dds, GEUVADIS = geuvadis),  :
   pandoc is not available!
>
>
!> countsimQCReport(ddsList = list("sim"=dds, "GEUVADIS"=geuvadis),
 +                  outputFile = "countsimReport.html",
 +                  outputDir = "./",
 +                  description = "Comparison of simulated transcript-level counts",
 +                  maxNForCorr = 50,
 +                  maxNForDisp = 50,
 +                  seed = 1,
 +                  calculateStatistics=FALSE, ignorePandoc=TRUE)
 Calculating dispersions. This can take some time, please be patient.
   C-c C-c
```

**Comment by csoneson** [comment]
Great - thanks!
